# Generated by Django 5.2.6 on 2025-09-17 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('html_body_template', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_templates',
            },
        ),
        migrations.CreateModel(
            name='MailTemplatesParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='emails.mailtemplates')),
            ],
            options={
                'db_table': 'mail_templates_params',
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SentMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(db_index=True, max_length=200)),
                ('template_params_hash', models.CharField(help_text='SHA-256 хэш параметров письма для проверки дубликатов', max_length=64)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='emails.mailtemplates')),
            ],
            options={
                'db_table': 'sent_mails',
                'unique_together': {('recipient_email', 'template', 'template_params_hash')},
            },
        ),
    ]
