# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import email_distribution_service_pb2 as email__distribution__service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in email_distribution_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmailDistributionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMail = channel.unary_unary(
                '/email_distribution.EmailDistribution/SendMail',
                request_serializer=email__distribution__service__pb2.SendMailRequest.SerializeToString,
                response_deserializer=email__distribution__service__pb2.SendMailResponse.FromString,
                _registered_method=True)
        self.GetStatsByEmail = channel.unary_unary(
                '/email_distribution.EmailDistribution/GetStatsByEmail',
                request_serializer=email__distribution__service__pb2.GetStatsByEmailRequest.SerializeToString,
                response_deserializer=email__distribution__service__pb2.GetStatsByEmailResponse.FromString,
                _registered_method=True)


class EmailDistributionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMail(self, request, context):
        """Отправка сообщений на переданные адреса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsByEmail(self, request, context):
        """Получение статистики писем по email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailDistributionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMail,
                    request_deserializer=email__distribution__service__pb2.SendMailRequest.FromString,
                    response_serializer=email__distribution__service__pb2.SendMailResponse.SerializeToString,
            ),
            'GetStatsByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsByEmail,
                    request_deserializer=email__distribution__service__pb2.GetStatsByEmailRequest.FromString,
                    response_serializer=email__distribution__service__pb2.GetStatsByEmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'email_distribution.EmailDistribution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('email_distribution.EmailDistribution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmailDistribution(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/email_distribution.EmailDistribution/SendMail',
            email__distribution__service__pb2.SendMailRequest.SerializeToString,
            email__distribution__service__pb2.SendMailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/email_distribution.EmailDistribution/GetStatsByEmail',
            email__distribution__service__pb2.GetStatsByEmailRequest.SerializeToString,
            email__distribution__service__pb2.GetStatsByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
