# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email_distribution_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'email_distribution_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n email_distribution_service.proto\x12\x12\x65mail_distribution\"\xb5\x01\n\x0fSendMailRequest\x12\x15\n\rtemplate_name\x18\x01 \x01(\t\x12\x12\n\nrecipients\x18\x02 \x03(\t\x12\x45\n\tvariables\x18\x03 \x03(\x0b\x32\x32.email_distribution.SendMailRequest.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"T\n\x13RecipientSendStatus\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.email_distribution.SendStatus\"L\n\x10SendMailResponse\x12\x38\n\x07results\x18\x01 \x03(\x0b\x32\'.email_distribution.RecipientSendStatus\"\'\n\x16GetStatsByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"5\n\rTemplateCount\x12\x15\n\rtemplate_name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"e\n\x17GetStatsByEmailResponse\x12\x12\n\ntotal_sent\x18\x01 \x01(\x04\x12\x36\n\x0b\x62y_template\x18\x02 \x03(\x0b\x32!.email_distribution.TemplateCount*N\n\nSendStatus\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x15\n\x11SKIPPED_DUPLICATE\x10\x03\x32\xd6\x01\n\x11\x45mailDistribution\x12U\n\x08SendMail\x12#.email_distribution.SendMailRequest\x1a$.email_distribution.SendMailResponse\x12j\n\x0fGetStatsByEmail\x12*.email_distribution.GetStatsByEmailRequest\x1a+.email_distribution.GetStatsByEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_distribution_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMAILREQUEST_VARIABLESENTRY']._loaded_options = None
  _globals['_SENDMAILREQUEST_VARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_SENDSTATUS']._serialized_start=603
  _globals['_SENDSTATUS']._serialized_end=681
  _globals['_SENDMAILREQUEST']._serialized_start=57
  _globals['_SENDMAILREQUEST']._serialized_end=238
  _globals['_SENDMAILREQUEST_VARIABLESENTRY']._serialized_start=190
  _globals['_SENDMAILREQUEST_VARIABLESENTRY']._serialized_end=238
  _globals['_RECIPIENTSENDSTATUS']._serialized_start=240
  _globals['_RECIPIENTSENDSTATUS']._serialized_end=324
  _globals['_SENDMAILRESPONSE']._serialized_start=326
  _globals['_SENDMAILRESPONSE']._serialized_end=402
  _globals['_GETSTATSBYEMAILREQUEST']._serialized_start=404
  _globals['_GETSTATSBYEMAILREQUEST']._serialized_end=443
  _globals['_TEMPLATECOUNT']._serialized_start=445
  _globals['_TEMPLATECOUNT']._serialized_end=498
  _globals['_GETSTATSBYEMAILRESPONSE']._serialized_start=500
  _globals['_GETSTATSBYEMAILRESPONSE']._serialized_end=601
  _globals['_EMAILDISTRIBUTION']._serialized_start=684
  _globals['_EMAILDISTRIBUTION']._serialized_end=898
# @@protoc_insertion_point(module_scope)
